#!/usr/bin/env python3
"""
Regenerate evdev_code_tables.py from vendor/linux/input-event-codes.h
usually /usr/include/linux/input-event-codes.h

Run after updating the vendored kernel UAPI copy:

  .github/scripts/gen-evdev-code-tables.py
"""
from __future__ import annotations

import re
from pathlib import Path

_DEFINE_RE = re.compile(
    r"^\s*#define\s+([A-Z][A-Z0-9_]*)\s+(0x[0-9A-Fa-f]+|\d+)\s*(?:/\*.*\*/)?\s*$"
)

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
HEADER_PATH = SCRIPT_DIR / "vendor/linux/input-event-codes.h"
OUT_PY = SCRIPT_DIR / "evdev_code_tables.py"
OUT_CPP_H = REPO_ROOT / "cpp/include/evdev_code_name_table.hpp"
OUT_CPP = REPO_ROOT / "cpp/src/evdev_code_name_table.cpp"


def parse_code_to_name(header_text: str, name_prefix: str) -> dict[int, str]:
    code_to_name: dict[int, str] = {}
    for line in header_text.splitlines():
        match = _DEFINE_RE.match(line)
        if not match:
            continue
        name, raw_value = match.group(1), match.group(2)
        if not name.startswith(name_prefix):
            continue
        code = int(raw_value, 0)
        if code not in code_to_name:
            code_to_name[code] = name
    return code_to_name


def format_dict(name: str, mapping: dict[int, str]) -> str:
    lines = [f"{name}: dict[int, str] = {{"]
    for code in sorted(mapping):
        lines.append(f"    {code}: {repr(mapping[code])},")
    lines.append("}")
    return "\n".join(lines)


def invert_name_to_code(*maps: dict[int, str]) -> dict[str, int]:
    name_to_code: dict[str, int] = {}
    for mapping in maps:
        for code, name in mapping.items():
            name_to_code.setdefault(name, code)
    return name_to_code


# Kernel gives BTN_MOUSE and BTN_LEFT the same code (0x110); prefer LEFT in generated tables.
_BTN_CODE_TO_FRIENDLY_NAME: dict[str, str] = {
    "BTN_MOUSE": "BTN_LEFT",
}


def apply_friendly_button_names(btn_map: dict[int, str]) -> None:
    for code, name in list(btn_map.items()):
        friendly = _BTN_CODE_TO_FRIENDLY_NAME.get(name)
        if friendly:
            btn_map[code] = friendly


def apply_friendly_button_names_to_name_table(name_to_code: dict[str, int]) -> None:
    for old_name, new_name in _BTN_CODE_TO_FRIENDLY_NAME.items():
        if old_name in name_to_code:
            code = name_to_code.pop(old_name)
            name_to_code.setdefault(new_name, code)


def write_cpp_name_table(name_to_code: dict[str, int]) -> None:
    lines = [
        "// Generated by gen-evdev-code-tables.py — do not edit.",
        "// Source: .github/scripts/vendor/linux/input-event-codes.h",
        '#include "evdev_code_name_table.hpp"',
        "",
        "#include <QHash>",
        "#include <QString>",
        "",
        "const QHash<QString, int> &evdevNameToCodeTable() {",
        "    static const QHash<QString, int> table = {",
    ]
    for name in sorted(name_to_code):
        code = name_to_code[name]
        lines.append(f'        {{QStringLiteral("{name}"), {code}}},')
    lines.extend(
        [
            "    };",
            "    return table;",
            "}",
            "",
        ]
    )
    OUT_CPP.parent.mkdir(parents=True, exist_ok=True)
    OUT_CPP.write_text("\n".join(lines), encoding="utf-8")

    header = """#pragma once

#include <QHash>
#include <QString>

/// BIND_PTT token (KEY_* / BTN_*) → Linux EV_KEY code. Generated from vendored input-event-codes.h.
const QHash<QString, int> &evdevNameToCodeTable();
"""
    OUT_CPP_H.write_text(header, encoding="utf-8")


def main() -> None:
    if not HEADER_PATH.is_file():
        raise SystemExit(f"missing vendored header: {HEADER_PATH}")

    header_text = HEADER_PATH.read_text(encoding="utf-8", errors="replace")
    key_map = parse_code_to_name(header_text, "KEY_")
    btn_map = parse_code_to_name(header_text, "BTN_")
    apply_friendly_button_names(btn_map)

    out = f'''# Generated by gen-evdev-code-tables.py — do not edit.
# Source: vendor/linux/input-event-codes.h (Linux input UAPI; SPDX GPL-2.0-only WITH Linux-syscall-note)
from __future__ import annotations

{format_dict("KEY_CODE_TO_NAME", key_map)}

{format_dict("BTN_CODE_TO_NAME", btn_map)}
'''
    OUT_PY.write_text(out, encoding="utf-8")
    name_to_code = invert_name_to_code(key_map, btn_map)
    apply_friendly_button_names_to_name_table(name_to_code)
    write_cpp_name_table(name_to_code)
    print(f"Wrote {OUT_PY} ({len(key_map)} KEY_*, {len(btn_map)} BTN_*)")
    print(f"Wrote {OUT_CPP_H} and {OUT_CPP} ({len(name_to_code)} name→code entries)")


if __name__ == "__main__":
    main()
